/* Generated By:JavaCC: Do not edit this line. ConfigStringParserConstants.java */
/*-----------------------------------------------------------------------------
 * ConfigStringParser (DO NOT EDIT - MACHINE GENERATED)
 *   JavaCC-generated parser for parsing a Config value String
 *-----------------------------------------------------------------------------
 */

package gov.va.med.lom.javaUtils.config;

public interface ConfigStringParserConstants {

  int EOF = 0;
  int WHITESPACE = 1;
  int WS_CHAR = 2;
  int QSTRING = 3;
  int STRING = 4;
  int QCHAR = 5;
  int PLUS = 6;
  int COMMA = 7;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<WS_CHAR>",
    "<QSTRING>",
    "<STRING>",
    "<QCHAR>",
    "<PLUS>",
    "<COMMA>",
  };

}
