/* Generated By:JavaCC: Do not edit this line. ConfigParserConstants.java */

package gov.va.med.lom.javaUtils.config;

public interface ConfigParserConstants {

  int EOF = 0;
  int KEYWORD = 3;
  int WHITESPACE = 4;
  int COMMENT = 5;
  int WS_CHAR = 6;
  int EOL = 7;
  int QSTRING = 8;
  int STRING = 9;
  int QCHAR = 10;
  int PLUS = 11;
  int COMMA = 12;
  int KW_CHAR = 13;
  int ASSIGN = 14;

  int DEFAULT = 0;
  int RHS = 1;

  String[] tokenImage = {
    "<EOF>",
    "\"[\"",
    "\"]\"",
    "<KEYWORD>",
    "<WHITESPACE>",
    "<COMMENT>",
    "<WS_CHAR>",
    "<EOL>",
    "<QSTRING>",
    "<STRING>",
    "<QCHAR>",
    "<PLUS>",
    "<COMMA>",
    "<KW_CHAR>",
    "<ASSIGN>",
  };

}
