avs.vi.localpath=/home/avs/files
avs.vi.remotepath=\\\\localhost\\avs
avs.vi.username=
avs.vi.password=
avs.vi.stscb=TESTCB^MAGGSIUI
avs.vi.ixtype=45
avs.vi.gdesc=After Visit Summary
avs.vi.ttype=104
avs.vi.pxpkg=8925
avs.vi.dflg=1